---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name truenas-garage-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        token: '{{ index . "SECRET_GARAGE_METRICS_TOKEN" }}'
  dataFrom:
    - extract:
        key: "shared.cluster-secrets"
