---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actual-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: actual-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: default.actual-budget
        property: client-secret
