---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name galene-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        config.json: |
          {
            "proxyURL": "https://meet.${SECRET_DOMAIN}/",
            "users": {
              "{{ index . "adminUsername" }}": {
                "password": {"type": "bcrypt", "key": "{{ index . "adminPasswordHash" }}"},
                "permissions": "admin"
              }
            }
          }
        turnKeyId: '{{ index . "turnKeyId" }}'
        turnApiToken: '{{ index . "turnApiToken" }}'
  dataFrom:
    - extract:
        key: "default.galene"
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name galene-groups
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        guests.json: |
          {
            "displayName": "Guests",
            "public": false,
            "max-clients": 16,
            "autolock": true,
            "allow-recording": false,
            "users": {
              "{{ index . "myUsername" }}": {
                "password": {"type": "bcrypt", "key": "{{ index . "myPasswordHash" }}"},
                "permissions": "op"
              }
            }
          }
  dataFrom:
    - extract:
        key: "default.galene"
