---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name memos-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        client-secret: '{{ index . "client-secret" }}'
        memos-idp-authelia.json: |
          {
            "uid": "00000001",
            "name": "Authelia",
            "type": "OAUTH2",
            "identifierFilter": "",
            "config": {
              "oauth2Config": {
                "clientId": "memos",
                "clientSecret": {{ index . "client-secret" | toJson }},
                "authUrl": "https://auth.${SECRET_DOMAIN}/api/oidc/authorization",
                "tokenUrl": "https://auth.${SECRET_DOMAIN}/api/oidc/token",
                "userInfoUrl": "https://auth.${SECRET_DOMAIN}/api/oidc/userinfo",
                "scopes": ["openid", "profile", "email"],
                "fieldMapping": {
                  "identifier": "preferred_username",
                  "displayName": "display_name",
                  "email": "email"
                }
              }
            }
          }
  dataFrom:
    - extract:
        # all available properties from the key will be synced
        key: "default.memos"
