# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mealie
    namespace: default
    annotations:
        reloader.stakater.com/match: "true"
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9PUC9B5NrhTwBvUYWlIVITUVgvnEI9l7Q5/e+aZsZ9yxu2zoh6XT,iv:2wUwPkALHdoSfKII+j5M74BVd0n7lxWZGTNqFnbiAFA=,tag:dbu4XPzW/Q3PUMuO3WsCBQ==,type:comment]
    #ENC[AES256_GCM,data:qvEtVWxMYEA2ml3HeVIOsZ98okQN9I5e/oqqGImBDQ==,iv:X7AYVgHjqxess9sblbzesBqeIp75Q7iDTU5uiI6BUzk=,tag:8TLTbPispM4x2S+nlxaW9A==,type:comment]
    #ENC[AES256_GCM,data:yNL9LPaP,iv:UsQ4o8qXwDBAG8AfRD7QEvVp2TCci5TvS0Pa60KAFBo=,tag:G+hudYZP68hGF9VNmup9PA==,type:comment]
    TOKEN_TIME: ENC[AES256_GCM,data:l64=,iv:DYkErEUIlUUhRoDuXfGs519qCsgGGxuT74EgKJm32/I=,tag:LkWQ5rJbmwz2+KjPkCztNg==,type:str]
    AUTO_BACKUP_ENABLED: ENC[AES256_GCM,data:ypcAIA==,iv:Zcn9nM5vqHqMbaiJPlX8GgpWJ7VKu2rBP6yU20wsrhE=,tag:nVop/GasY0zYOfiv4l+Nmg==,type:str]
    ALLOW_SIGNUP: ENC[AES256_GCM,data:zFU5Mp8=,iv:4aZD7v+Fnx2G/oGLaZg27D/juBW7j4Oo6dyEa3qhzp8=,tag:cdJIiW0LZBQ+J0Nlyg2XfA==,type:str]
    #ENC[AES256_GCM,data:9OBURUOALL0Hokrl7w1o1sg=,iv:at/xP4prADs+3AFBD+YIJItAOAohjkSC1yfhgx1zO2M=,tag:YtIpwfWfjZhKiRUvzOLOag==,type:comment]
    SMTP_HOST: ENC[AES256_GCM,data:S2xP3QhrsXG+8pDnf3WsVrU=,iv:A5Wky0FQETTej3kWh2VjVYe0HMuQLw1vo/muTrRh/5o=,tag:OYMY3J4J8wQ7Zp85QkfsTA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:Zpix,iv:rO3HLncJ6p42Mg3ewLBpDg8zJmSQAVDmEYtGKuaJQic=,tag:WE5J49wsGmgBZaeKL7kmxw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:OukLS6CVr98OOZoexa9f0rUgoRNl10uDPOE=,iv:BMX4xKh9jNJawGg9eZyfV+MFnZvdmeOnkPqieltXGRI=,tag:Wvy08r83fcNl6u2yGJ/V/A==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:mLAYVnOPy4l8/RIE5qtScA==,iv:Q9FEaZYLMfURuxRoAQRhQ6po0sCvHa7c/VRihuAuFW4=,tag:YVDLDr2LsnhQ8iCtDZJUiw==,type:str]
    SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:5PM7,iv:5j8PBGsiEljFD4ED072nlW1fiHWeZNPUm6BcLKdPFH8=,tag:dvKuG64xkTVV9caLd6cTUg==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:KJVtIYEj,iv:oDHjNGiT+lzuMN+O8he5o+sApuTtZQ8iZlVgdCuS49Q=,tag:xB1xyWs5y04vu9Aw2CcRBw==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:n99Q/C8/cW+ZhcXcwho59PT/XEdTequPLQ==,iv:5PksyEtiDN0vPSHU9lo2+Y3I3s6rxpCL+I9FatiBFo4=,tag:iJIsDrjuHOEDaB+2xRAqxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaFdncjlycnZTTCtmSnVW
            Q3hDZWNKQ0xwZDRjU3JFbXpVUjJDUzMrMTBVCllQT2laNkpqeStZMFZyZ0hyOW9s
            WkJiOVVXM1hWbVBzUFFiT3JSTGNCaE0KLS0tIFVmOGRjbnY2dDNTbmo1WFhtR3Nh
            VklaOUpUWGF1RCtYZ1p4Q29vSFNaS3cKcq5dGzxr9whQ/hE4+uGohPR9Oux3vPde
            7EfUsMG0XCKnDHSn8eLstyyMJw+H5ctgpAi/f3vfzs0ca2LHFpp0Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a7nyvwztvzudynvx92z6tegdxcmudhdh7fh6ty6sqs8n4gh2lelqkqk9aa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T16:04:44Z"
    mac: ENC[AES256_GCM,data:9y1StTHtt+OQIvMahcP08E22r3FXlW9Hoq0yccwouBPEVUS8bbc/n1GEcgmZD+XmHoQHXWxj+VVzML5ncsJ3U8YrOYmqrY5lB94zJWNftbQZhdsFus7kuaVNx/X+Cai211Tyw8pfF6PwTTkhxw/VTPftFeHa96YW5aRxXH8jYiI=,iv:E6Gyka+4ubQD8KGlG2ue8r47VUdUKBNk/REW/n3tEuA=,tag:XGFNOLx7WyDNiSIN7oPO8g==,type:str]
    version: 3.13.3
