---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app volsync
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    manageCRDs: true
    metrics:
      disableAuth: true

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: *app
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: volsync
              spec:
                template:
                  spec:
                    containers:
                      - name: manager
                        volumeMounts:
                          - name: tz-config
                            mountPath: /etc/localtime
                    volumes:
                      - name: tz-config
                        hostPath:
                          path: /usr/share/zoneinfo/America/New_York
                          type: File
