---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Flate

on:
  pull_request:
    branches:
      - main
    paths:
      - kubernetes/**/*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Flate - Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Flate
        uses: home-operations/flate/action@0fc37fae10cf3c265294f6adebc6d6c100c74ea5 # v0.4.10
        with:
          cache: "true"
          version: 0.4.10

      - name: Test Flux resources
        run: flate test all --path ./kubernetes/flux/cluster
